### ISSUE TITLE
Range don't include last element by default

### ISSUE THREAD

**Issue by spokvulcan** [jakobwesthoff/the_ray_tracer_challenge_in_rust#1]
Hi i found a little mistake in your test, Range don't include last element by default, so you don't need to do -1 here.

https://github.com/jakobwesthoff/the_ray_tracer_challenge_in_rust/blob/1696169b884652049821ad94e1717ea18bc006cc/src/canvas.rs#L207-L211

**Comment by jakobwesthoff** [comment]
Thanks for the hint. It is fixed now.
